Fixed volume checking in emit sound
dreamstalker/rehlds pull request #341
Opened 2017-02-10 03:10 UTC by WPMGPRoSToTeMa

2017-02-10 03:36 UTC, LevShisterov commented on rehlds/engine/pr_cmds.cpp
> +	if (!(0.0 <= volume && volume <= 1.0))
Please use similar form:
`if (volume < 0.0 || volume > 1.0)`
Thanks.

2017-02-10 15:42 UTC, In-line commented
Maybe we don't need crash server with `Sys_Error(...)`. I think it's not such critical error to do that.

2017-02-14 10:07 UTC, spark512 commented
> Maybe we don't need crash server with Sys_Error(...). I think it's not such critical error to do that.

Yeah, why crash the server due to an improper sound? Just throw an error and ignore/remove the sound, the server can keep going..

2017-02-14 15:57 UTC, WPMGPRoSToTeMa commented
Without crash a lot of people will just ignore that error, this is not good, because the reasons of bad arguments can be non-obvious (like we got from regamedll func_breakable), but additional info should help. We can show error(s), clamp arguments in needed range and play sound (if there is no problems with `channel` arg).

2017-02-14 16:03 UTC, In-line commented
@WPMGPRoSToTeMa It's good idea too. Why did not you use the lamba with auto parameters? I think it can be more readable.

2017-02-14 17:39 UTC, WPMGPRoSToTeMa commented
@In-line you can't stringize expression without macro.

2017-02-24 08:28 UTC, spark512 commented
Any progress on this one?

2017-05-05 12:47 UTC, In-line commented
@WPMGPRoSToTeMa Ping.

2018-04-21 08:14 UTC, WPMGPRoSToTeMa commented
Can someone of collaborators remove ignore of this PR in TeamCity?

2018-04-22 04:40 UTC, s1lentq commented
Done.

2018-09-17 18:32 UTC, theshadowz commented
Is it going to be merged?

2021-06-17 16:34 UTC, wopox1337 requested changes

2021-06-17 16:34 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [&](double varValue, char const *varName, double min, double max) {
Why use `[&]` instead `[=]` for declaration? The context parameters are not changed, only read.

2021-06-17 16:50 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [&](double varValue, char const *varName, double min, double max) {
Done https://github.com/dreamstalker/rehlds/pull/341/commits/e064ac8e3da6131ca64d45eeb070233ecc88a100

2021-06-17 16:51 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	if (!(0.0 <= volume && volume <= 1.0))
Done https://github.com/dreamstalker/rehlds/pull/341/commits/cb3cdc59c0ce00183514e84a17cc05586db6e60d

2021-06-17 17:23 UTC, wopox1337 approved these changes

2021-06-17 18:48 UTC, WPMGPRoSToTeMa reviewed
@s1lentq which behavior changes are allowed to be not `#ifdef`ed?

2021-06-17 23:10 UTC, wopox1337 commented
@WPMGPRoSToTeMa Fix is not important. And readability exceeds usefulness #ifdef REHLDS_FIXES

2021-06-17 23:14 UTC, WPMGPRoSToTeMa commented on rehlds/engine/sv_main.cpp
> +	auto clampBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Pass `value` by ref as you're changing it.

2021-06-17 23:16 UTC, WPMGPRoSToTeMa commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Template lambdas are in C++20. As I know this project is targeting C++14.

2021-06-17 23:21 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Yes, you're right. Then I don't know how to do it for C++14.

2021-06-17 23:22 UTC, wopox1337 commented on rehlds/engine/sv_main.cpp
> +	auto clampBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Thanks! Done https://github.com/dreamstalker/rehlds/pull/341/commits/7978f70487f158881a1bd1ce7c4e71e942812689

2021-06-17 23:46 UTC, WPMGPRoSToTeMa commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
@wopox1337 you can turn it into a separate static function and pass `__func__`, `entity` and `sample` as parameters.

2021-06-17 23:57 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Thank you! I'll fix it tomorrow.

2021-06-18 03:19 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
> Or you can use auto instead, so there will be 3 template parameters.

Then we will lose the type check for the compiler.

2021-06-19 10:11 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
Unfortunately, no suitable solution with lambda functions was found. So in this PR we leave only the essence - fixing the error of the original HLDS without refactoring. 🤔

2021-06-19 10:12 UTC, merged

2021-06-19 10:12 UTC, s1lentq approved these changes

2021-06-19 16:17 UTC, WPMGPRoSToTeMa commented on rehlds/engine/pr_cmds.cpp
>  		Sys_Error("%s: volume = %i", __func__, volume);
@wopox1337 @s1lentq 
Note that the merged changes doesn't include a fix for this line, it should be:
```C++
Sys_Error("%s: volume = %f", __func__, volume);
```

2021-06-19 16:20 UTC, wopox1337 commented on rehlds/engine/pr_cmds.cpp
>  		Sys_Error("%s: volume = %i", __func__, volume);
Already fixed in master branch

2021-09-06 19:32 UTC, Hun1eR commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
@wopox1337 Actually you can use auto instead of template parameters. And this is should work on c++14:
```cpp
auto checkBounds = [=, func = __func__](auto value, char const *name, decltype(value) min, decltype(value) max)
```

2021-09-06 19:57 UTC, WPMGPRoSToTeMa commented on rehlds/engine/pr_cmds.cpp
> +	auto checkBounds = [=, func = __func__]<typename T>(T value, char const *name, T min, T max)
@Hun1eR your suggestion looks great!