New CVar `sv_rcon_allowexternal` for control external usage of RCon
dreamstalker/rehlds pull request #796
Opened 2021-01-05 16:52 UTC by GiovaniFerraroTrivelli

Some panels, like OpenGamePanel, use an option to send commands through Rcon. In my case, for security, I disabled Rcon (rcon_password "") but I need an option to send commands without entering to the server.

I added a cvar, sv_rcon_allowexternal (0/1) that allows or disallows the usage of Rcon from externals IPs. Also, it logs when this cvar value is 0 and someone tries to use Rcon.

This is more simple than #587, which is a very good idea. In the future it could be improved to match this suggestion.

(This PR recreates correctly #710)

2021-01-10 17:19 UTC, afwn90cj93201nixr2e1re commented
.

2021-01-27 22:34 UTC, theAsmodai commented on rehlds/engine/sv_main.cpp
> +		Con_Printf("Rcon denied from %s\n", NET_AdrToString(*net_from_));
Please hide it under sv_rcon_condebug.value check

2021-06-17 21:12 UTC, GiovaniFerraroTrivelli commented on rehlds/engine/sv_main.cpp
> +		Con_Printf("Rcon denied from %s\n", NET_AdrToString(*net_from_));
Done

2021-06-18 06:27 UTC, afwn90cj93201nixr2e1re commented
.

2021-06-18 06:32 UTC, afwn90cj93201nixr2e1re commented
.

2021-06-18 06:50 UTC, afwn90cj93201nixr2e1re commented
.

2021-06-18 11:23 UTC, GiovaniFerraroTrivelli commented
Conflict resolved

2021-06-18 13:06 UTC, afwn90cj93201nixr2e1re commented
.

2021-06-19 04:13 UTC, afwn90cj93201nixr2e1re commented
.

2021-06-19 20:04 UTC, wopox1337 submitted a review, later dismissed

2021-06-19 20:11 UTC, wopox1337 commented
> This is more simple than #587

I do not agree with you.

The problem you described refers to problems with game server control panels (like OGP). The control panel should use stdin for local control.

**Remote** CONsole = (RCon). 

The proposed functionality is a "crutch" for a remote control method called RCon.

2021-06-19 20:16 UTC, wopox1337 requested changes

2021-06-19 20:16 UTC, wopox1337 commented on rehlds/engine/sv_main.cpp
> +	if(!sv_rcon_allowexternal.value && !NET_CompareBaseAdr(*net_from_, net_local_adr))
`if(` -> `if (`

2021-06-19 20:16 UTC, wopox1337 commented on rehlds/engine/sv_main.cpp
> +			Log_Printf("Rcon denied from %s\n", NET_AdrToString(*net_from_));
Add better description

```cpp
Con_Printf("External Rcon denied from %s\n", NET_AdrToString(*net_from_));
Log_Printf("External Rcon denied from %s\n", NET_AdrToString(*net_from_));
```

2021-06-19 20:18 UTC, wopox1337 requested changes

2021-06-19 20:18 UTC, wopox1337 commented on rehlds/engine/sv_main.cpp
> +	if(!sv_rcon_allowexternal.value && !NET_CompareBaseAdr(*net_from_, net_local_adr))
`if(` -> `if (`

2021-08-03 17:06 UTC, Maxi605 commented
@theAsmodai can we get this?

2021-08-09 14:50 UTC, wopox1337 approved these changes

2024-01-17 17:40 UTC, closed without merging