Implemented PF_Precache_* hooks
dreamstalker/rehlds pull request #903
Opened 2022-03-05 09:26 UTC by ShadowsAdi

- PF_precache_generic_I
- PF_precache_model_I
- PF_precache_sound_I

Based on https://github.com/dreamstalker/rehlds/pull/900
Requested in https://github.com/s1lentq/reapi/issues/248

2022-03-05 09:54 UTC, ShadowsAdi commented
If the reviewer wants, he could merge this pull and closehttps://github.com/dreamstalker/rehlds/pull/900, because it contains it.

2022-03-05 11:08 UTC, StevenKal commented
Well, since you implemented "SV_CheckUserInfo" inside this PR, and since, this PR contains multiple hooks, I think you can close your other one for simplicity. But add you added it too, in the description.
Also, in order to have something "almost complete about precaching stuff", it will be nice if you could also add "precache_event" (EV_Precache) & "SV_AddResource" to your PR. Thanks in advance!

2022-03-05 12:09 UTC, StevenKal commented
Nice! Now I think we could submit other hooks requests to it! Hehehe!

Without abusing, I am thinking of "SV_ClientPrintf" (similar to "Con_Printf", but send to client, so very useful, you can put it in top of the list below "its friend"!), "Sys_Error" & "Host_Error" too (useful to prevent server crash on an error which may not be "critical for it", or, if we use an internal code to fix, as example I have a map where I have a "Bad surface extents ..." error shit, I blocked the function, map runs fine & I did not constated third-party troubles!).
There are other functions, but as I said, I do not want to abuse with your time & devotion!

2022-03-05 12:55 UTC, ShadowsAdi commented
> Without abusing, I am thinking of "SV_ClientPrintf" (similar to "Con_Printf", but send to client [like when you type in-game some commands as "status", this uses this one], so very useful, you can put it in top of the list below "its friend"!), "Sys_Error" & "Host_Error" too (useful to prevent server crash on an error which may not be "critical for it", or, if we use an internal code to fix, as example I have a map where I have a "Bad surface extents ..." error shit, so I could not run it, then I blocked the function, map runs fine & I did not constated third-party troubles!). There are other functions, but as I said, I do not want to abuse with your time & devotion!

 I will implement "SV_ClientPrintf" in another PR, because it's more cleaner.
 About "Sys_Error" and "Host_Error" they are crashing the server or client before bad things happen. They should NOT be blocked with a reason.
 
> I guess you could rename the PR into "Implemented more hooks"! With such listing!

 How I said, I will implement rest of chains in another PRs. This PR should've been dedicated only to precache resources hooks, but I merged "SV_CheckUserInfo" into my master branch and SV_AddResource could be assimilated with resources.
 
> PS: I do not recommend to make the functions from the structure "RehldsFuncs_t" (g_RehldsApiFuncs) point to another "redirected function" (like now "SV_AddResource_api"), except if there is a conflit somewhere while compiling, or, if you add additionnal code inside that famous "_api" function. Mainly due to the fact we loose the possibility to get the address of the "real function", via this structure (& by using "g_RehldsApiFuncs" as base address).

 Thank you for your recommendation. Finished the implementation. It can be downloaded from my reapi's fork ( Actions tab: https://github.com/ShadowsAdi/rehlds/actions/runs/1938126909 )

2022-03-05 14:41 UTC, StevenKal commented
You can rename your PR into "Implemented more hooks", something like, only your branch name "precache-hooks" can be confusing, but that's just a branch name, the approver will edit the title in the comit when it will merge & people may not pay much attention to your branch name by reading the commit's details.
Since there is "SV_CheckUserInfo" which is "out of precache context", I think "SV_ClientPrintf" could also been added, and in the top, to be with his friend "ConPrintf"! Hehehe!

The errors functions are for "critical" stuff, as you said, but a few of them are not much very critical (some are just here to tell you passed a bad parameter, as example), & you can prevent server crash without generating third-party issues, or, use a specific code from the related message, to fix the issue (by hooking the functions where the error is called). But those functions are not as much important as the ones you added, and we can "live without".

Good work!

2022-03-11 15:08 UTC, ShadowsAdi commented
Implemented `SV_ClientPrintf` hook

2022-03-21 17:04 UTC, wopox1337 requested changes

2022-03-21 17:04 UTC, wopox1337 commented on rehlds/engine/host.cpp
> -		string[ARRAYSIZE(string) - 1] = 0;
?

2022-03-21 17:04 UTC, wopox1337 commented
please do not refactor along with the implementation of the new functionality.

2022-03-21 17:08 UTC, wopox1337 commented
remove all refactoring from this PR please

2022-03-21 18:16 UTC, ShadowsAdi commented
Everything should be alright now, @wopox1337

2022-04-13 09:11 UTC, LevShisterov commented on rehlds/engine/host.cpp
> +	g_RehldsHookchains.m_SV_ClientPrintf.callChain(SV_ClientPrintf_internal, Dest);
I think you should pass size of the buffer along with the buffer itself. Otherwise people using this API to modify message content may blindly hit buffer overflow.

2022-04-13 12:29 UTC, StevenKal commented on rehlds/engine/host.cpp
> +	g_RehldsHookchains.m_SV_ClientPrintf.callChain(SV_ClientPrintf_internal, Dest);
Should not be needed as AMXX's ReAPI args are sized to max 1024 length which is the max buffer size of "SV_ClientPrintf", besides, internally here (in "SV_ClientPrintf_internal") it is "memcpy" again to a 1024 size buffer.
A note in the doc "do not exceed 1023 characters" or "The maximum length of the dest buffer is limited to 1023 characters" could be enough.

2022-04-13 18:18 UTC, ShadowsAdi commented on rehlds/engine/host.cpp
> +	g_RehldsHookchains.m_SV_ClientPrintf.callChain(SV_ClientPrintf_internal, Dest);
My mistake, gonna fix that.

2022-04-14 03:42 UTC, LevShisterov commented on rehlds/engine/host.cpp
> +	g_RehldsHookchains.m_SV_ClientPrintf.callChain(SV_ClientPrintf_internal, Dest);
@StevenKal, I look at this as C++ API, and AMXX is the only one of many consumers.
And I missed that in this PR it wasn't supposed to modify content and argument is declared as `const char *`, so buffer size is not required. Though, I think content modifying is not so useles feature, to be implemented.

2022-07-22 15:09 UTC, UnrealKaraulov commented
Any news ? 👀 

Nice feature, please merge it! :)

2022-07-26 11:29 UTC, StevenKal commented
> Any news ? 👀
> 
> Nice feature, please merge it! :)

Corpses everywhere nowadays! All fucking dead! Disappointing huh!

2022-07-28 20:10 UTC, RauliTop commented
> Yes, nice feature. But corpses everywhere nowadays! All fucking dead! Disappointing huh! Population in the world keeps increasing, but it seems Aliens have kidnapped a lot of people to bring them "we do not know where"!

Where place did you escape from?

2022-07-28 21:42 UTC, StevenKal commented
I am one of the aliens (other group of aliens), I can not reveal secret defense information about possible location of others aliens lab!

2022-09-19 09:08 UTC, wopox1337 approved these changes

2022-09-19 11:20 UTC, merged